version: '3'
volumes:
  node_modules:
services:
  db:
    image: mdillon/postgis
    container_name: db
  shelterly-dev:
    image: freeradical3:wsgi
    container_name: shelterly-dev
    volumes:
      - ./config:/home/shelterly/config
    ports:
      - "80:80"
      - "8001:8001"
      - "3001:3001"
    depends_on:
      - db
