version: '3'
volumes:
  node_modules:
services:
  db:
    image: mdillon/postgis
    container_name: db
  shelterly:
    image: 13311e9510a4
    #image: freeradical3/rams:dev
    container_name: shelterly
    volumes:
      - ./config:/home/shelterly/config
      - node_modules:/home/shelterly/frontend/node_modules
    ports:
      - "8000:8000"
      - "3000:3000"
    depends_on:
      - db
