version: '3'
volumes:
  node_modules:
services:
  db:
    image: mdillon/postgis
    container_name: db
  shelterly:
    image: trevorskaggs/shelterly:latest
    container_name: shelterly
    volumes:
      - ./config:/home/shelterly/config
      - /home/shelterly/venv
    ports:
      - "8000:8000"
      - "3000:3000"
    depends_on:
      - db
