# Generated by Django 3.0.5 on 2020-04-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_auto_20200321_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='color_notes',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='last_seen',
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='chip_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='chipped',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='markings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
